apiVersion: v1
kind: Namespace
metadata:
  name: recursing-lamarr
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recursing-lamarr
spec:
  project: default
  source:
    repoURL: https://github.com/sam-andaluri/saas-tenant-recursing-lamarr.git
    targetRevision: HEAD
    path: tier
  destination:
    server: https://kubernetes.default.svc
    namespace: recursing-lamarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true